name: "CI"
on:
  pull_request:
  push:

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4
            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4
            - name: Run ESLint
              run: npm run eslint
    build:
        name: Compile
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4
            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4
            - name: Compile
              run: npm run build

    unit-tests:
        name: Unit Tests
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v1
          - name: download roblox install script
            run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/install.py" -OutFile install.py
          - name: download settings file
            run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/GlobalSettings_13.xml" -OutFile GlobalSettings_13.xml
          - name: install pip deps
            run: pip install wget psutil
          - name: install roblox
            run: python install.py "${{ secrets.ROBLOSECURITY }}"
          - name: install roblox-ts
            run: npm i -g roblox-ts@1.0.0-beta.15
          - name: install local npm packages
            run: npm i --production=false
          - name: compile typescript code
            run: npm run build
          - name: install foreman
            uses: rojo-rbx/setup-foreman@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
          - name: install foreman packages (rojo, run-in-roblox)
            run: foreman install
          - name: run rojo build
            run: rojo build -o .\\unit_tests.rbxlx
          - name: run tests
            run: run-in-roblox --place .\\unit_tests.rbxlx --script .\\spec.server.lua
        

    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs: [lint, build, unit-tests]
        if: github.ref == 'refs/heads/master'
        environment: Roblox
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4
            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4
            - name: Compile
              run: npm run build
            - name: Install Foreman
              uses: Roblox/setup-foreman@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build place
              run: rojo build -o PLACE.rbxl
            - name: Publish place
              run: | 
                    curl  --verbose --location --request POST 'https://apis.roblox.com/universes/v1/3139551611/places/8169822582/versions?versionType=Published' --header 'x-api-key:${{ secrets.PLACE_TOKEN }}' --header 'Content-Type: application/octet-stream' --data-binary @PLACE.rbxl